/**
 * The bundled content set: the four categories with their sections, the four
 * stories, and the Gronings sound inventory.
 *
 * The structure is small and always needed, so it is imported eagerly. Stories
 * are large and only one is needed at a time, so each is a separate chunk
 * fetched when a level opens.
 *
 * The JSON is generated by `scripts/build-content.mjs`; the casts are the one
 * place where its shape is trusted to match `$lib/types`.
 */
import type { Category, CategoryContent, Level, Section, Sound, Story } from '$lib/types';
import categoriesJson from './categories.json';
import soundsJson from './sounds.json';

export const categories = categoriesJson as unknown as CategoryContent[];
export const sounds = soundsJson as unknown as Sound[];

/** The sounds that may be offered as a distractor. */
export const distractorSounds = sounds.filter((sound) => sound.distractor !== false);

const soundsBySpelling = new Map(sounds.map((sound) => [sound.sound, sound]));

export const getSound = (spelling: string): Sound | undefined => soundsBySpelling.get(spelling);

/* -------------------------------------------------------------------------- */
/* Categories, sections and levels                                            */
/* -------------------------------------------------------------------------- */

const categoriesById = new Map(categories.map((category) => [category.id, category]));

export const getCategory = (id: Category): CategoryContent | undefined => categoriesById.get(id);

export function getSection(category: Category, section: string): Section | undefined {
	return getCategory(category)?.sections.find((candidate) => candidate.id === section);
}

/** The localStorage key of a level, for example "luisteren.woorden.bragel". */
export const levelId = (category: Category, section: string, story: string): string =>
	`${category}.${section}.${story}`;

function toLevel(category: Category, section: string, story: string, index: number): Level {
	return { id: levelId(category, section, story), category, section, story, number: index + 1 };
}

/** The levels of one section, in the order their cards are shown. */
export function sectionLevels(category: Category, section: string): Level[] {
	const stories = getSection(category, section)?.stories ?? [];
	return stories.map((story, index) => toLevel(category, section, story, index));
}

/** Every level of one category. */
export function categoryLevels(category: Category): Level[] {
	return (getCategory(category)?.sections ?? []).flatMap((section) =>
		sectionLevels(category, section.id)
	);
}

/** All 44 levels. Also the set of level keys that may exist in localStorage. */
export function allLevels(): Level[] {
	return categories.flatMap((category) => categoryLevels(category.id));
}

/* -------------------------------------------------------------------------- */
/* Stories                                                                    */
/* -------------------------------------------------------------------------- */

const storyModules = import.meta.glob('./stories/*.json', { import: 'default' }) as Record<
	string,
	() => Promise<unknown>
>;

const loaded = new Map<string, Story>();

/** Fetches one story, or returns it straight away once it has been fetched. */
export async function loadStory(key: string): Promise<Story> {
	const cached = loaded.get(key);
	if (cached) return cached;

	const load = storyModules[`./stories/${key}.json`];
	if (!load) throw new Error(`No story named "${key}" in the content set.`);

	const story = (await load()) as Story;
	loaded.set(key, story);
	return story;
}

/** A story that has already been fetched, for use where awaiting is not an option. */
export const getLoadedStory = (key: string): Story | undefined => loaded.get(key);
